package com.plainsimple.spaceships.engine.ui;

/*
Inputs that can be generated by the UI.
 */
public enum UIInputId {
    SHOOT,
    MOVE_UP,
    MOVE_DOWN,
    PAUSE,
    RESUME,
    RESTART,
    MUTE,
    UN_MUTE,
}
