package com.galaxyrun.engine;

/**
 * Created by Stefan on 8/26/2020.
 */

public enum EventID {
    BULLET_FIRED,
    ALIEN_DIED,
    COIN_COLLECTED,
    SPACESHIP_DAMAGED,
    SPACESHIP_KILLED,
    SPACESHIP_INVISIBLE,
    BULLET_COLLIDED,
    ALIEN_FIRED_BULLET,
    ALIEN_SHOT,
    ALIEN_BULLET_OFF_SCREEN,
    ALIEN_BULLET_COLLIDED,
    ASTEROID_SHOT,
    ASTEROID_DESTROYED,
    SPRITE_SPAWNED,
    GAME_STARTED,
    GAME_FINISHED
}
